SET SQLBLANKLINES ON;
SET DEFINE OFF;
SET SERVEROUTPUT ON;
-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 01: DATABASE SCHEMA DDL
-- Compatible with Oracle Database 19c, 21c, and 23ai Free
-- ============================================================================

SET SQLBLANKLINES ON;

-- Clean up existing objects in reverse dependency order
BEGIN
    FOR t IN (
        SELECT table_name FROM all_tables 
        WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
          AND table_name IN (
            'JOURNEYROUTE', 'JOURNEYLEG', 'TRANSACTION', 'WALLET', 'SMARTCARD',
            'PASSENGERFARECLASS', 'PASSENGER', 'FARECLASS', 'SEGMENTFARE',
            'AFFECTEDSTATION', 'AFFECTEDSEGMENT', 'INCIDENT',
            'ROUTETRANSFER', 'STATION_PAIR_TRANSFER', 'SEGMENT', 'ROUTESTOP',
            'ROUTE', 'STATION'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- SPATIAL GRAPH ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE STATION (
    StationID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(100)       NOT NULL,
    City                VARCHAR2(60)        NOT NULL,
    Latitude            NUMBER(9,6)         NOT NULL,
    Longitude           NUMBER(9,6)         NOT NULL,
    Address             VARCHAR2(255),
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_STATION_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE ROUTE (
    RouteID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(100)       NOT NULL,
    "Mode"              VARCHAR2(20)        NOT NULL,
    Operator            VARCHAR2(100)       NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_ROUTE_MODE CHECK ("Mode" IN ('Metro', 'Bus', 'Train')),
    CONSTRAINT CHK_ROUTE_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE ROUTESTOP (
    RouteStopID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RouteID             NUMBER              NOT NULL,
    StationID           NUMBER              NOT NULL,
    Sequence            NUMBER(4)           NOT NULL,
    PlatformNumber      VARCHAR2(20),
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_ROUTESTOP_ROUTE   FOREIGN KEY (RouteID)   REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_ROUTESTOP_STATION FOREIGN KEY (StationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROUTE_SEQUENCE    UNIQUE (RouteID, Sequence),
    CONSTRAINT CHK_ROUTESTOP_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE SEGMENT (
    SegmentID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RouteID             NUMBER              NOT NULL,
    FromRouteStopID     NUMBER              NOT NULL,
    ToRouteStopID       NUMBER              NOT NULL,
    Distance            NUMBER(6,2)         NOT NULL, -- kilometers
    ScheduledTime       NUMBER(4)           NOT NULL, -- minutes
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SEGMENT_ROUTE         FOREIGN KEY (RouteID)         REFERENCES ROUTE(RouteID)         ON DELETE CASCADE,
    CONSTRAINT FK_SEGMENT_FROMSTOP      FOREIGN KEY (FromRouteStopID) REFERENCES ROUTESTOP(RouteStopID) ON DELETE CASCADE,
    CONSTRAINT FK_SEGMENT_TOSTOP        FOREIGN KEY (ToRouteStopID)   REFERENCES ROUTESTOP(RouteStopID) ON DELETE CASCADE,
    CONSTRAINT UQ_SEGMENT_PAIR          UNIQUE (RouteID, FromRouteStopID, ToRouteStopID),
    CONSTRAINT CHK_SEGMENT_ACTIVE       CHECK (IsActive IN (0, 1)),
    CONSTRAINT CHK_SEGMENT_DISTANCE     CHECK (Distance > 0),
    CONSTRAINT CHK_SEGMENT_TIME         CHECK (ScheduledTime > 0)
);

-- ----------------------------------------------------------------------------
-- TRANSFER ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE STATION_PAIR_TRANSFER (
    TransferID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FromStationID       NUMBER              NOT NULL,
    ToStationID         NUMBER              NOT NULL,
    WalkingDistance     NUMBER(6)           NOT NULL, -- meters
    WalkingTime         NUMBER(4)           NOT NULL, -- minutes
    IsDirectConnection  NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SPTRANSFER_FROMSTATION FOREIGN KEY (FromStationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT FK_SPTRANSFER_TOSTATION   FOREIGN KEY (ToStationID)   REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_SPTRANSFER_PAIR        UNIQUE (FromStationID, ToStationID),
    CONSTRAINT CHK_SPTRANSFER_DIFF       CHECK (FromStationID <> ToStationID),
    CONSTRAINT CHK_SPTRANSFER_DIRECT     CHECK (IsDirectConnection IN (0, 1))
);

CREATE TABLE ROUTETRANSFER (
    RouteTransferID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FromRouteID         NUMBER              NOT NULL,
    ToRouteID           NUMBER              NOT NULL,
    CommonStationID     NUMBER              NOT NULL,
    TransferTime        NUMBER(4)           NOT NULL, -- minutes
    MinimumWaitTime     NUMBER(4)           DEFAULT 2 NOT NULL, -- minutes
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_RTRANSFER_FROMROUTE   FOREIGN KEY (FromRouteID)     REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_RTRANSFER_TOROUTE     FOREIGN KEY (ToRouteID)       REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_RTRANSFER_STATION     FOREIGN KEY (CommonStationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_RTRANSFER_CONFIG      UNIQUE (FromRouteID, ToRouteID, CommonStationID),
    CONSTRAINT CHK_RTRANSFER_DIFF       CHECK (FromRouteID <> ToRouteID),
    CONSTRAINT CHK_RTRANSFER_ACTIVE     CHECK (IsActive IN (0, 1))
);

-- ----------------------------------------------------------------------------
-- DISRUPTION ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE INCIDENT (
    IncidentID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title               VARCHAR2(150)       NOT NULL,
    Description         VARCHAR2(1000),
    StartTime           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    EndTime             TIMESTAMP,
    Severity            VARCHAR2(20)        NOT NULL,
    CONSTRAINT CHK_INCIDENT_SEVERITY CHECK (Severity IN ('Minor', 'Moderate', 'Major', 'Critical')),
    CONSTRAINT CHK_INCIDENT_TIMEFRAME CHECK (EndTime IS NULL OR EndTime >= StartTime)
);

CREATE TABLE AFFECTEDSEGMENT (
    AffectedSegmentID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IncidentID          NUMBER              NOT NULL,
    SegmentID           NUMBER              NOT NULL,
    StatusType          VARCHAR2(20)        NOT NULL,
    DelayMinutes        NUMBER(4)           DEFAULT 0 NOT NULL,
    CONSTRAINT FK_AFFSEG_INCIDENT FOREIGN KEY (IncidentID) REFERENCES INCIDENT(IncidentID) ON DELETE CASCADE,
    CONSTRAINT FK_AFFSEG_SEGMENT  FOREIGN KEY (SegmentID)  REFERENCES SEGMENT(SegmentID)   ON DELETE CASCADE,
    CONSTRAINT CHK_AFFSEG_STATUS  CHECK (StatusType IN ('Delayed', 'Suspended', 'Rerouted', 'Normal'))
);

CREATE TABLE AFFECTEDSTATION (
    AffectedStationID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IncidentID          NUMBER              NOT NULL,
    StationID           NUMBER              NOT NULL,
    StatusType          VARCHAR2(20)        NOT NULL,
    Reason              VARCHAR2(255),
    CONSTRAINT FK_AFFSTAT_INCIDENT FOREIGN KEY (IncidentID) REFERENCES INCIDENT(IncidentID) ON DELETE CASCADE,
    CONSTRAINT FK_AFFSTAT_STATION  FOREIGN KEY (StationID)  REFERENCES STATION(StationID)   ON DELETE CASCADE,
    CONSTRAINT CHK_AFFSTAT_STATUS  CHECK (StatusType IN ('Open', 'PartiallyClosed', 'Closed', 'Congested'))
);

-- ----------------------------------------------------------------------------
-- PRICING ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE FARECLASS (
    FareClassID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(60)        NOT NULL,
    DiscountPercentage  NUMBER(5,2)         DEFAULT 0.00 NOT NULL,
    RequiresVerification NUMBER(1)          DEFAULT 0 NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_FARECLASS_DISCOUNT CHECK (DiscountPercentage BETWEEN 0 AND 100),
    CONSTRAINT CHK_FARECLASS_VERIF    CHECK (RequiresVerification IN (0, 1)),
    CONSTRAINT CHK_FARECLASS_ACTIVE   CHECK (IsActive IN (0, 1))
);

CREATE TABLE SEGMENTFARE (
    SegmentFareID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SegmentID           NUMBER              NOT NULL,
    BaseAmount          NUMBER(8,2)         NOT NULL,
    ValidFrom           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ValidTo             TIMESTAMP,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SEGFARE_SEGMENT   FOREIGN KEY (SegmentID) REFERENCES SEGMENT(SegmentID) ON DELETE CASCADE,
    CONSTRAINT CHK_SEGFARE_AMOUNT   CHECK (BaseAmount >= 0),
    CONSTRAINT CHK_SEGFARE_ACTIVE   CHECK (IsActive IN (0, 1)),
    CONSTRAINT CHK_SEGFARE_TIMEFRAME CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom)
);

-- ----------------------------------------------------------------------------
-- PASSENGER & ACCOUNT ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE PASSENGER (
    PassengerID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email               VARCHAR2(150)       NOT NULL CONSTRAINT UQ_PASSENGER_EMAIL UNIQUE,
    FirstName           VARCHAR2(60)        NOT NULL,
    LastName            VARCHAR2(60)        NOT NULL,
    DateOfBirth         DATE,
    Phone               VARCHAR2(30),
    RegistrationDate    TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE PASSENGERFARECLASS (
    PassengerFareClassID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PassengerID         NUMBER              NOT NULL,
    FareClassID         NUMBER              NOT NULL,
    ValidFrom           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ValidTo             TIMESTAMP,
    VerificationStatus  VARCHAR2(20)        DEFAULT 'Pending' NOT NULL,
    CONSTRAINT FK_PFC_PASSENGER FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT FK_PFC_FARECLASS FOREIGN KEY (FareClassID) REFERENCES FARECLASS(FareClassID) ON DELETE CASCADE,
    CONSTRAINT CHK_PFC_STATUS   CHECK (VerificationStatus IN ('Pending', 'Approved', 'Rejected', 'Expired'))
);

CREATE TABLE SMARTCARD (
    SmartCardID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PassengerID         NUMBER              NOT NULL,
    CardNumber          VARCHAR2(30)        NOT NULL CONSTRAINT UQ_SMARTCARD_NUM UNIQUE,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    ActivationDate      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ExpiryDate          TIMESTAMP           NOT NULL,
    CONSTRAINT FK_SMARTCARD_PASSENGER FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT CHK_SMARTCARD_ACTIVE   CHECK (IsActive IN (0, 1))
);

CREATE TABLE WALLET (
    WalletID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SmartCardID         NUMBER              NOT NULL CONSTRAINT UQ_WALLET_SMARTCARD UNIQUE,
    Balance             NUMBER(10,2)        DEFAULT 0.00 NOT NULL,
    LastUpdated         TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_WALLET_SMARTCARD FOREIGN KEY (SmartCardID) REFERENCES SMARTCARD(SmartCardID) ON DELETE CASCADE,
    CONSTRAINT CHK_WALLET_BALANCE  CHECK (Balance >= 0.00),
    CONSTRAINT CHK_WALLET_ACTIVE   CHECK (IsActive IN (0, 1))
);

-- ----------------------------------------------------------------------------
-- TRANSACTION & JOURNEY ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE TRANSACTION (
    TransactionID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WalletID            NUMBER              NOT NULL,
    TransactionType     VARCHAR2(20)        NOT NULL,
    Amount              NUMBER(10,2)        NOT NULL,
    Timestamp           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    Status              VARCHAR2(20)        DEFAULT 'Completed' NOT NULL,
    Reference           VARCHAR2(100),
    CONSTRAINT FK_TX_WALLET  FOREIGN KEY (WalletID) REFERENCES WALLET(WalletID) ON DELETE CASCADE,
    CONSTRAINT CHK_TX_TYPE   CHECK (TransactionType IN ('TopUp', 'FareDeduction', 'Refund', 'Adjustment')),
    CONSTRAINT CHK_TX_STATUS CHECK (Status IN ('Pending', 'Completed', 'Failed', 'Reversed'))
);

CREATE TABLE JOURNEYLEG (
    JourneyLegID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SmartCardID         NUMBER              NOT NULL,
    PassengerID         NUMBER              NOT NULL,
    FromStationID       NUMBER              NOT NULL,
    ToStationID         NUMBER,
    TapInTime           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    TapOutTime          TIMESTAMP,
    FareDeducted        NUMBER(8,2)         DEFAULT 0.00 NOT NULL,
    FareClassAtTime     VARCHAR2(60)        NOT NULL,
    Status              VARCHAR2(20)        DEFAULT 'InProgress' NOT NULL,
    CONSTRAINT FK_JLEG_SMARTCARD FOREIGN KEY (SmartCardID)   REFERENCES SMARTCARD(SmartCardID) ON DELETE CASCADE,
    CONSTRAINT FK_JLEG_PASSENGER FOREIGN KEY (PassengerID)   REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT FK_JLEG_FROMSTAT  FOREIGN KEY (FromStationID) REFERENCES STATION(StationID),
    CONSTRAINT FK_JLEG_TOSTAT    FOREIGN KEY (ToStationID)   REFERENCES STATION(StationID),
    CONSTRAINT CHK_JLEG_STATUS   CHECK (Status IN ('InProgress', 'Completed', 'Cancelled', 'Incomplete'))
);

CREATE TABLE JOURNEYROUTE (
    JourneyRouteUsedID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JourneyLegID        NUMBER              NOT NULL,
    RouteID             NUMBER              NOT NULL,
    Sequence            NUMBER(3)           DEFAULT 1 NOT NULL,
    BoardingTime        TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    AlightingTime       TIMESTAMP,
    CONSTRAINT FK_JROUTE_LEG   FOREIGN KEY (JourneyLegID) REFERENCES JOURNEYLEG(JourneyLegID) ON DELETE CASCADE,
    CONSTRAINT FK_JROUTE_ROUTE FOREIGN KEY (RouteID)      REFERENCES ROUTE(RouteID)           ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- PERFORMANCE INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX IDX_ROUTESTOP_STATION   ON ROUTESTOP(StationID);
CREATE INDEX IDX_SEGMENT_ROUTE       ON SEGMENT(RouteID);
CREATE INDEX IDX_SEGMENT_FROMSTOP    ON SEGMENT(FromRouteStopID);
CREATE INDEX IDX_SEGMENT_TOSTOP      ON SEGMENT(ToRouteStopID);
CREATE INDEX IDX_RTRANSFER_COMMON    ON ROUTETRANSFER(CommonStationID, FromRouteID, ToRouteID);
CREATE INDEX IDX_AFFSEG_LOOKUP       ON AFFECTEDSEGMENT(SegmentID, StatusType);
CREATE INDEX IDX_AFFSTAT_LOOKUP      ON AFFECTEDSTATION(StationID, StatusType);
CREATE INDEX IDX_INCIDENT_ACTIVE     ON INCIDENT(StartTime, EndTime);
CREATE INDEX IDX_SEGFARE_LOOKUP      ON SEGMENTFARE(SegmentID, IsActive);
CREATE INDEX IDX_TRANSACTION_WALLET  ON TRANSACTION(WalletID, Timestamp);
CREATE INDEX IDX_JOURNEYLEG_CARD     ON JOURNEYLEG(SmartCardID, Status);

-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 02: SEED MOCK DATA
-- Inserts realistic multi-modal network, fares, passengers, and incidents
-- ============================================================================

SET DEFINE OFF;
SET SQLBLANKLINES ON;

-- 1. STATIONS
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (101, 'Central Hub', 'Metro City', 40.7128, -74.0060, '100 Grand Concourse', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (102, 'Financial Center', 'Metro City', 40.7075, -74.0090, '25 Wall St', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (103, 'Midtown West', 'Metro City', 40.7549, -73.9840, '400 8th Ave', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (104, 'Metro North', 'Metro City', 40.7890, -73.9500, '850 Grand Blvd', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (105, 'Tech Park', 'Metro City', 40.7300, -73.9950, '50 Innovation Way', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (106, 'Harbor View', 'Metro City', 40.6900, -74.0200, '12 Ferry Terminal Rd', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (107, 'University Village', 'Metro City', 40.7295, -73.9965, '30 Scholars Plaza', 1);
INSERT INTO STATION (StationID, Name, City, Latitude, Longitude, Address, IsActive) VALUES (108, 'Airport Terminal 1', 'Metro City', 40.6413, -73.7781, 'Airport Pkwy Bldg 1', 1);

-- 2. ROUTES
INSERT INTO ROUTE (RouteID, Name, "Mode", Operator, IsActive) VALUES (1, 'Red Metro Line', 'Metro', 'City Transit Authority', 1);
INSERT INTO ROUTE (RouteID, Name, "Mode", Operator, IsActive) VALUES (2, 'Blue Metro Line', 'Metro', 'City Transit Authority', 1);
INSERT INTO ROUTE (RouteID, Name, "Mode", Operator, IsActive) VALUES (3, 'Express Commuter Train', 'Train', 'Regional Rail Corp', 1);
INSERT INTO ROUTE (RouteID, Name, "Mode", Operator, IsActive) VALUES (4, 'Downtown Express Bus 101', 'Bus', 'Metro Bus Systems', 1);

-- 3. ROUTE STOPS
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (1001, 1, 104, 1, '1A', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (1002, 1, 103, 2, '1A', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (1003, 1, 101, 3, '1A', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (1004, 1, 102, 4, '1A', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (1005, 1, 106, 5, '1A', 1);

INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (2001, 2, 105, 1, '2B', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (2002, 2, 101, 2, '2B', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (2003, 2, 107, 3, '2B', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (2004, 2, 108, 4, '2B', 1);

INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (3001, 3, 104, 1, 'T1', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (3002, 3, 101, 2, 'T2', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (3003, 3, 108, 3, 'T3', 1);

INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (4001, 4, 103, 1, 'Bay 4', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (4002, 4, 105, 2, 'Bay 1', 1);
INSERT INTO ROUTESTOP (RouteStopID, RouteID, StationID, Sequence, PlatformNumber, IsActive) VALUES (4003, 4, 102, 3, 'Bay 2', 1);

-- 4. SEGMENTS
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5001, 1, 1001, 1002, 4.5, 7, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5002, 1, 1002, 1003, 3.8, 6, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5003, 1, 1003, 1004, 2.2, 4, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5004, 1, 1004, 1005, 3.1, 5, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5005, 2, 2001, 2002, 2.8, 5, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5006, 2, 2002, 2003, 1.9, 4, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5007, 2, 2003, 2004, 14.2, 18, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5008, 3, 3001, 3002, 8.1, 11, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5009, 3, 3002, 3003, 18.5, 22, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5010, 4, 4001, 4002, 3.5, 12, 1);
INSERT INTO SEGMENT (SegmentID, RouteID, FromRouteStopID, ToRouteStopID, Distance, ScheduledTime, IsActive) VALUES (5011, 4, 4002, 4003, 2.4, 9, 1);

-- 5. TRANSFERS
INSERT INTO STATION_PAIR_TRANSFER (TransferID, FromStationID, ToStationID, WalkingDistance, WalkingTime, IsDirectConnection) VALUES (6001, 105, 107, 180, 3, 1);
INSERT INTO STATION_PAIR_TRANSFER (TransferID, FromStationID, ToStationID, WalkingDistance, WalkingTime, IsDirectConnection) VALUES (6002, 107, 105, 180, 3, 1);
INSERT INTO STATION_PAIR_TRANSFER (TransferID, FromStationID, ToStationID, WalkingDistance, WalkingTime, IsDirectConnection) VALUES (6003, 102, 106, 550, 8, 0);
INSERT INTO STATION_PAIR_TRANSFER (TransferID, FromStationID, ToStationID, WalkingDistance, WalkingTime, IsDirectConnection) VALUES (6004, 106, 102, 550, 8, 0);

INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7001, 1, 2, 101, 4, 3, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7002, 2, 1, 101, 4, 3, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7003, 1, 3, 101, 6, 5, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7004, 3, 1, 101, 6, 5, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7005, 2, 3, 101, 7, 5, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7006, 3, 2, 101, 7, 5, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7007, 1, 3, 104, 5, 4, 1);
INSERT INTO ROUTETRANSFER (RouteTransferID, FromRouteID, ToRouteID, CommonStationID, TransferTime, MinimumWaitTime, IsActive) VALUES (7008, 3, 1, 104, 5, 4, 1);

-- 6. INCIDENTS & DISRUPTIONS
INSERT INTO INCIDENT (IncidentID, Title, Description, StartTime, EndTime, Severity) VALUES (8001, 'Signal Failure at Downtown Tunnel', 'Track circuit fault between Central and Financial Center', TO_TIMESTAMP('2026-09-19 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Major');
INSERT INTO INCIDENT (IncidentID, Title, Description, StartTime, EndTime, Severity) VALUES (8002, 'Escalator Maintenance', 'North concourse escalator undergoing overhaul', TO_TIMESTAMP('2026-09-18 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-20 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Minor');
INSERT INTO INCIDENT (IncidentID, Title, Description, StartTime, EndTime, Severity) VALUES (8003, 'Express Track Flooding', 'Flash flood warning impacting Commuter Train', TO_TIMESTAMP('2026-09-19 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Critical');

INSERT INTO AFFECTEDSEGMENT (AffectedSegmentID, IncidentID, SegmentID, StatusType, DelayMinutes) VALUES (8101, 8001, 5003, 'Delayed', 15);
INSERT INTO AFFECTEDSEGMENT (AffectedSegmentID, IncidentID, SegmentID, StatusType, DelayMinutes) VALUES (8102, 8003, 5008, 'Suspended', 999);

INSERT INTO AFFECTEDSTATION (AffectedStationID, IncidentID, StationID, StatusType, Reason) VALUES (8201, 8002, 104, 'PartiallyClosed', 'Escalator outage affecting Platform 1A');
INSERT INTO AFFECTEDSTATION (AffectedStationID, IncidentID, StationID, StatusType, Reason) VALUES (8202, 8003, 104, 'Congested', 'Passenger backlog due to suspended train service');

-- 7. FARE CLASSES & FARES
INSERT INTO FARECLASS (FareClassID, Name, DiscountPercentage, RequiresVerification, IsActive) VALUES (1, 'Standard Adult', 0.00, 0, 1);
INSERT INTO FARECLASS (FareClassID, Name, DiscountPercentage, RequiresVerification, IsActive) VALUES (2, 'Student', 30.00, 1, 1);
INSERT INTO FARECLASS (FareClassID, Name, DiscountPercentage, RequiresVerification, IsActive) VALUES (3, 'Senior Citizen', 50.00, 1, 1);
INSERT INTO FARECLASS (FareClassID, Name, DiscountPercentage, RequiresVerification, IsActive) VALUES (4, 'Child Under 12', 100.00, 0, 1);

INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9001, 5001, 2.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9002, 5002, 2.25, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9003, 5003, 2.00, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9004, 5004, 2.25, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9005, 5005, 2.00, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9006, 5006, 1.75, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9007, 5007, 5.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9008, 5008, 4.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9009, 5009, 8.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9010, 5010, 1.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO SEGMENTFARE (SegmentFareID, SegmentID, BaseAmount, ValidFrom, ValidTo, IsActive) VALUES (9011, 5011, 1.50, TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 1);

-- 8. PASSENGERS & SMARTCARDS & WALLETS
INSERT INTO PASSENGER (PassengerID, Email, FirstName, LastName, DateOfBirth, Phone, RegistrationDate) VALUES (10001, 'alice.chen@example.com', 'Alice', 'Chen', TO_DATE('1998-04-12', 'YYYY-MM-DD'), '+15550101', TO_TIMESTAMP('2026-02-15 09:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PASSENGER (PassengerID, Email, FirstName, LastName, DateOfBirth, Phone, RegistrationDate) VALUES (10002, 'marcus.vance@example.com', 'Marcus', 'Vance', TO_DATE('1972-11-03', 'YYYY-MM-DD'), '+15550102', TO_TIMESTAMP('2026-03-01 14:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PASSENGER (PassengerID, Email, FirstName, LastName, DateOfBirth, Phone, RegistrationDate) VALUES (10003, 'elena.rostova@example.com', 'Elena', 'Rostova', TO_DATE('2004-08-25', 'YYYY-MM-DD'), '+15550103', TO_TIMESTAMP('2026-05-18 11:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PASSENGER (PassengerID, Email, FirstName, LastName, DateOfBirth, Phone, RegistrationDate) VALUES (10004, 'david.kim@example.com', 'David', 'Kim', TO_DATE('1958-01-30', 'YYYY-MM-DD'), '+15550104', TO_TIMESTAMP('2026-06-10 16:30:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PASSENGERFARECLASS (PassengerFareClassID, PassengerID, FareClassID, ValidFrom, ValidTo, VerificationStatus) VALUES (11001, 10001, 1, TO_TIMESTAMP('2026-02-15 09:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 'Approved');
INSERT INTO PASSENGERFARECLASS (PassengerFareClassID, PassengerID, FareClassID, ValidFrom, ValidTo, VerificationStatus) VALUES (11002, 10002, 1, TO_TIMESTAMP('2026-03-01 14:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2029-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 'Approved');
INSERT INTO PASSENGERFARECLASS (PassengerFareClassID, PassengerID, FareClassID, ValidFrom, ValidTo, VerificationStatus) VALUES (11003, 10003, 2, TO_TIMESTAMP('2026-05-18 11:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2027-05-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 'Approved');
INSERT INTO PASSENGERFARECLASS (PassengerFareClassID, PassengerID, FareClassID, ValidFrom, ValidTo, VerificationStatus) VALUES (11004, 10004, 3, TO_TIMESTAMP('2026-06-10 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2030-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), 'Approved');

INSERT INTO SMARTCARD (SmartCardID, PassengerID, CardNumber, IsActive, ActivationDate, ExpiryDate) VALUES (20001, 10001, 'MC-9901-4412-0001', 1, TO_TIMESTAMP('2026-02-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2031-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SMARTCARD (SmartCardID, PassengerID, CardNumber, IsActive, ActivationDate, ExpiryDate) VALUES (20002, 10002, 'MC-9901-4412-0002', 1, TO_TIMESTAMP('2026-03-01 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2031-03-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SMARTCARD (SmartCardID, PassengerID, CardNumber, IsActive, ActivationDate, ExpiryDate) VALUES (20003, 10003, 'MC-9901-4412-0003', 1, TO_TIMESTAMP('2026-05-18 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2031-05-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SMARTCARD (SmartCardID, PassengerID, CardNumber, IsActive, ActivationDate, ExpiryDate) VALUES (20004, 10004, 'MC-9901-4412-0004', 1, TO_TIMESTAMP('2026-06-10 16:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2031-06-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO WALLET (WalletID, SmartCardID, Balance, LastUpdated, IsActive) VALUES (30001, 20001, 42.50, TO_TIMESTAMP('2026-09-19 08:05:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WALLET (WalletID, SmartCardID, Balance, LastUpdated, IsActive) VALUES (30002, 20002, 18.00, TO_TIMESTAMP('2026-09-18 19:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WALLET (WalletID, SmartCardID, Balance, LastUpdated, IsActive) VALUES (30003, 20003, 25.75, TO_TIMESTAMP('2026-09-19 07:45:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WALLET (WalletID, SmartCardID, Balance, LastUpdated, IsActive) VALUES (30004, 20004, 50.00, TO_TIMESTAMP('2026-09-17 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

-- 9. TRANSACTIONS & JOURNEYS
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40001, 30001, 'TopUp', 50.00, TO_TIMESTAMP('2026-09-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TOPUP-CC-89410');
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40002, 30001, 'FareDeduction', 4.75, TO_TIMESTAMP('2026-09-18 08:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TRIP-LEG-50001');
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40003, 30001, 'FareDeduction', 2.75, TO_TIMESTAMP('2026-09-19 08:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TRIP-LEG-50002');
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40004, 30002, 'TopUp', 20.00, TO_TIMESTAMP('2026-09-18 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TOPUP-CASH-1022');
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40005, 30003, 'TopUp', 30.00, TO_TIMESTAMP('2026-09-10 12:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TOPUP-CC-33921');
INSERT INTO TRANSACTION (TransactionID, WalletID, TransactionType, Amount, Timestamp, Status, Reference) VALUES (40006, 30003, 'FareDeduction', 4.25, TO_TIMESTAMP('2026-09-19 07:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed', 'TRIP-LEG-50003');

INSERT INTO JOURNEYLEG (JourneyLegID, SmartCardID, PassengerID, FromStationID, ToStationID, TapInTime, TapOutTime, FareDeducted, FareClassAtTime, Status) VALUES (50001, 20001, 10001, 104, 101, TO_TIMESTAMP('2026-09-18 08:25:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-18 08:45:00', 'YYYY-MM-DD HH24:MI:SS'), 4.75, 'Standard Adult', 'Completed');
INSERT INTO JOURNEYLEG (JourneyLegID, SmartCardID, PassengerID, FromStationID, ToStationID, TapInTime, TapOutTime, FareDeducted, FareClassAtTime, Status) VALUES (50002, 20001, 10001, 101, 106, TO_TIMESTAMP('2026-09-19 07:48:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 08:05:00', 'YYYY-MM-DD HH24:MI:SS'), 2.75, 'Standard Adult', 'Completed');
INSERT INTO JOURNEYLEG (JourneyLegID, SmartCardID, PassengerID, FromStationID, ToStationID, TapInTime, TapOutTime, FareDeducted, FareClassAtTime, Status) VALUES (50003, 20003, 10003, 105, 108, TO_TIMESTAMP('2026-09-19 07:15:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 07:45:00', 'YYYY-MM-DD HH24:MI:SS'), 4.25, 'Student', 'Completed');
INSERT INTO JOURNEYLEG (JourneyLegID, SmartCardID, PassengerID, FromStationID, ToStationID, TapInTime, TapOutTime, FareDeducted, FareClassAtTime, Status) VALUES (50004, 20002, 10002, 103, 102, TO_TIMESTAMP('2026-09-19 08:20:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 0.00, 'Standard Adult', 'InProgress');

INSERT INTO JOURNEYROUTE (JourneyRouteUsedID, JourneyLegID, RouteID, Sequence, BoardingTime, AlightingTime) VALUES (60001, 50001, 1, 1, TO_TIMESTAMP('2026-09-18 08:27:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-18 08:43:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO JOURNEYROUTE (JourneyRouteUsedID, JourneyLegID, RouteID, Sequence, BoardingTime, AlightingTime) VALUES (60002, 50002, 1, 1, TO_TIMESTAMP('2026-09-19 07:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 08:03:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO JOURNEYROUTE (JourneyRouteUsedID, JourneyLegID, RouteID, Sequence, BoardingTime, AlightingTime) VALUES (60003, 50003, 2, 1, TO_TIMESTAMP('2026-09-19 07:18:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-19 07:43:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO JOURNEYROUTE (JourneyRouteUsedID, JourneyLegID, RouteID, Sequence, BoardingTime, AlightingTime) VALUES (60004, 50004, 4, 1, TO_TIMESTAMP('2026-09-19 08:22:00', 'YYYY-MM-DD HH24:MI:SS'), NULL);

COMMIT;

-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 03: SECURITY & USER ACCESS VIEWS
-- Enforces kernel-level read-only access (WITH READ ONLY) for the user portal
-- ============================================================================

SET SQLBLANKLINES ON;

-- 1. Active Stations Directory for Start/End selection
CREATE OR REPLACE VIEW V_USER_ACTIVE_STATIONS AS
SELECT 
    s.StationID,
    s.Name AS StationName,
    s.City,
    s.Latitude,
    s.Longitude,
    s.Address,
    NVL(ast.StatusType, 'Normal') AS StationStatus,
    ast.Reason AS DisruptionReason
FROM STATION s
LEFT JOIN (
    SELECT 
        af.StationID,
        af.StatusType,
        af.Reason
    FROM AFFECTEDSTATION af
    JOIN INCIDENT inc ON af.IncidentID = inc.IncidentID
    WHERE SYSTIMESTAMP BETWEEN inc.StartTime AND NVL(inc.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
) ast ON s.StationID = ast.StationID
WHERE s.IsActive = 1
WITH READ ONLY;

-- 2. Transit Network Adjacency Graph with live disruption telemetry
CREATE OR REPLACE VIEW V_USER_NETWORK_GRAPH AS
SELECT 
    seg.SegmentID,
    r.RouteID,
    r.Name AS RouteName,
    r."Mode" AS TransitMode,
    r.Operator,
    rs_from.Sequence AS FromSequence,
    st_from.StationID AS FromStationID,
    st_from.Name AS FromStationName,
    rs_to.Sequence AS ToSequence,
    st_to.StationID AS ToStationID,
    st_to.Name AS ToStationName,
    seg.Distance AS DistanceKm,
    seg.ScheduledTime AS ScheduledMinutes,
    NVL(sf.BaseAmount, 2.00) AS BaseFare,
    NVL(aff.StatusType, 'Normal') AS DisruptionStatus,
    NVL(aff.DelayMinutes, 0) AS DelayMinutes,
    (seg.ScheduledTime + NVL(aff.DelayMinutes, 0)) AS EffectiveMinutes,
    inc.Title AS IncidentTitle,
    inc.Severity AS IncidentSeverity
FROM SEGMENT seg
JOIN ROUTE r ON seg.RouteID = r.RouteID AND r.IsActive = 1
JOIN ROUTESTOP rs_from ON seg.FromRouteStopID = rs_from.RouteStopID AND rs_from.IsActive = 1
JOIN STATION st_from ON rs_from.StationID = st_from.StationID AND st_from.IsActive = 1
JOIN ROUTESTOP rs_to ON seg.ToRouteStopID = rs_to.RouteStopID AND rs_to.IsActive = 1
JOIN STATION st_to ON rs_to.StationID = st_to.StationID AND st_to.IsActive = 1
LEFT JOIN SEGMENTFARE sf ON seg.SegmentID = sf.SegmentID 
    AND sf.IsActive = 1 
    AND SYSTIMESTAMP BETWEEN sf.ValidFrom AND NVL(sf.ValidTo, SYSTIMESTAMP + INTERVAL '1' DAY)
LEFT JOIN (
    SELECT 
        a.SegmentID,
        a.StatusType,
        a.DelayMinutes,
        a.IncidentID
    FROM AFFECTEDSEGMENT a
    JOIN INCIDENT i ON a.IncidentID = i.IncidentID
    WHERE SYSTIMESTAMP BETWEEN i.StartTime AND NVL(i.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
) aff ON seg.SegmentID = aff.SegmentID
LEFT JOIN INCIDENT inc ON aff.IncidentID = inc.IncidentID
WHERE seg.IsActive = 1
WITH READ ONLY;

-- 3. Live Disruption & Incident Advisory Bulletin
CREATE OR REPLACE VIEW V_USER_ACTIVE_DISRUPTIONS AS
SELECT 
    inc.IncidentID,
    inc.Title,
    inc.Description,
    inc.Severity,
    TO_CHAR(inc.StartTime, 'YYYY-MM-DD HH24:MI') AS DisruptionStart,
    TO_CHAR(inc.EndTime, 'YYYY-MM-DD HH24:MI') AS EstimatedRestoration,
    'SEGMENT' AS AffectedEntityType,
    aff_seg.SegmentID AS AffectedEntityID,
    r.Name || ' (' || st_from.Name || ' -> ' || st_to.Name || ')' AS ImpactDetails,
    aff_seg.StatusType,
    aff_seg.DelayMinutes
FROM INCIDENT inc
JOIN AFFECTEDSEGMENT aff_seg ON inc.IncidentID = aff_seg.IncidentID
JOIN SEGMENT s ON aff_seg.SegmentID = s.SegmentID
JOIN ROUTE r ON s.RouteID = r.RouteID
JOIN ROUTESTOP rs_from ON s.FromRouteStopID = rs_from.RouteStopID
JOIN STATION st_from ON rs_from.StationID = st_from.StationID
JOIN ROUTESTOP rs_to ON s.ToRouteStopID = rs_to.RouteStopID
JOIN STATION st_to ON rs_to.StationID = st_to.StationID
WHERE SYSTIMESTAMP BETWEEN inc.StartTime AND NVL(inc.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
UNION ALL
SELECT 
    inc.IncidentID,
    inc.Title,
    inc.Description,
    inc.Severity,
    TO_CHAR(inc.StartTime, 'YYYY-MM-DD HH24:MI') AS DisruptionStart,
    TO_CHAR(inc.EndTime, 'YYYY-MM-DD HH24:MI') AS EstimatedRestoration,
    'STATION' AS AffectedEntityType,
    aff_stat.StationID AS AffectedEntityID,
    st.Name || ' (' || st.City || ')' AS ImpactDetails,
    aff_stat.StatusType,
    0 AS DelayMinutes
FROM INCIDENT inc
JOIN AFFECTEDSTATION aff_stat ON inc.IncidentID = aff_stat.IncidentID
JOIN STATION st ON aff_stat.StationID = st.StationID
WHERE SYSTIMESTAMP BETWEEN inc.StartTime AND NVL(inc.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
WITH READ ONLY;

-- 4. User Safe SmartCard & Wallet View (No PII leak)
CREATE OR REPLACE VIEW V_USER_CARD_WALLET AS
SELECT 
    sc.CardNumber,
    sc.IsActive AS CardIsActive,
    TO_CHAR(sc.ExpiryDate, 'YYYY-MM-DD') AS ExpirationDate,
    w.WalletID,
    w.Balance,
    w.IsActive AS WalletIsActive,
    TO_CHAR(w.LastUpdated, 'YYYY-MM-DD HH24:MI:SS') AS LastUpdated,
    p.PassengerID,
    p.FirstName || ' ' || SUBSTR(p.LastName, 1, 1) || '.' AS PassengerDisplayName,
    NVL(fc.Name, 'Standard Adult') AS FareClassName,
    NVL(fc.DiscountPercentage, 0) AS DiscountPercentage
FROM SMARTCARD sc
JOIN WALLET w ON sc.SmartCardID = w.SmartCardID
JOIN PASSENGER p ON sc.PassengerID = p.PassengerID
LEFT JOIN PASSENGERFARECLASS pfc ON p.PassengerID = pfc.PassengerID 
    AND pfc.VerificationStatus = 'Approved'
    AND SYSTIMESTAMP BETWEEN pfc.ValidFrom AND NVL(pfc.ValidTo, SYSTIMESTAMP + INTERVAL '1' DAY)
LEFT JOIN FARECLASS fc ON pfc.FareClassID = fc.FareClassID AND fc.IsActive = 1
WITH READ ONLY;

-- 5. User Travel History View
CREATE OR REPLACE VIEW V_USER_JOURNEY_HISTORY AS
SELECT 
    jl.JourneyLegID,
    sc.CardNumber,
    st_from.Name AS OriginStation,
    st_to.Name AS DestinationStation,
    TO_CHAR(jl.TapInTime, 'YYYY-MM-DD HH24:MI:SS') AS TapInTimeFormatted,
    TO_CHAR(jl.TapOutTime, 'YYYY-MM-DD HH24:MI:SS') AS TapOutTimeFormatted,
    jl.FareDeducted,
    jl.FareClassAtTime,
    jl.Status
FROM JOURNEYLEG jl
JOIN SMARTCARD sc ON jl.SmartCardID = sc.SmartCardID
JOIN STATION st_from ON jl.FromStationID = st_from.StationID
LEFT JOIN STATION st_to ON jl.ToStationID = st_to.StationID
ORDER BY jl.TapInTime DESC
WITH READ ONLY;

-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 04: ADMIN DISRUPTION & NETWORK MANAGEMENT PACKAGE
-- Provides atomic, transactional stored procedures for administrator operations
-- ============================================================================

CREATE OR REPLACE PACKAGE PKG_BETTERTRAVEL_ADMIN AS
    -- Incident lifecycle
    PROCEDURE PRC_REPORT_INCIDENT (
        p_title         IN  VARCHAR2,
        p_description   IN  VARCHAR2,
        p_severity      IN  VARCHAR2,
        p_start_time    IN  TIMESTAMP DEFAULT SYSTIMESTAMP,
        p_end_time      IN  TIMESTAMP DEFAULT NULL,
        o_incident_id   OUT NUMBER
    );

    PROCEDURE PRC_DISRUPT_SEGMENT (
        p_incident_id   IN  NUMBER,
        p_segment_id    IN  NUMBER,
        p_status_type   IN  VARCHAR2,
        p_delay_minutes IN  NUMBER DEFAULT 0
    );

    PROCEDURE PRC_DISRUPT_STATION (
        p_incident_id   IN  NUMBER,
        p_station_id    IN  NUMBER,
        p_status_type   IN  VARCHAR2,
        p_reason        IN  VARCHAR2
    );

    PROCEDURE PRC_RESOLVE_INCIDENT (
        p_incident_id   IN  NUMBER
    );

    -- Network configuration
    PROCEDURE PRC_ADD_STATION (
        p_name          IN  VARCHAR2,
        p_city          IN  VARCHAR2,
        p_lat           IN  NUMBER,
        p_lng           IN  NUMBER,
        p_address       IN  VARCHAR2,
        o_station_id    OUT NUMBER
    );

    -- Wallet operations (kiosk / customer care top-up)
    PROCEDURE PRC_TOPUP_WALLET (
        p_card_number   IN  VARCHAR2,
        p_amount        IN  NUMBER,
        p_reference     IN  VARCHAR2,
        o_new_balance   OUT NUMBER
    );
END PKG_BETTERTRAVEL_ADMIN;
/

CREATE OR REPLACE PACKAGE BODY PKG_BETTERTRAVEL_ADMIN AS

    PROCEDURE PRC_REPORT_INCIDENT (
        p_title         IN  VARCHAR2,
        p_description   IN  VARCHAR2,
        p_severity      IN  VARCHAR2,
        p_start_time    IN  TIMESTAMP DEFAULT SYSTIMESTAMP,
        p_end_time      IN  TIMESTAMP DEFAULT NULL,
        o_incident_id   OUT NUMBER
    ) IS
    BEGIN
        IF p_severity NOT IN ('Minor', 'Moderate', 'Major', 'Critical') THEN
            RAISE_APPLICATION_ERROR(-20001, 'Invalid severity level. Must be Minor, Moderate, Major, or Critical.');
        END IF;

        INSERT INTO INCIDENT (Title, Description, Severity, StartTime, EndTime)
        VALUES (p_title, p_description, p_severity, NVL(p_start_time, SYSTIMESTAMP), p_end_time)
        RETURNING IncidentID INTO o_incident_id;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_REPORT_INCIDENT;

    PROCEDURE PRC_DISRUPT_SEGMENT (
        p_incident_id   IN  NUMBER,
        p_segment_id    IN  NUMBER,
        p_status_type   IN  VARCHAR2,
        p_delay_minutes IN  NUMBER DEFAULT 0
    ) IS
        v_dummy NUMBER;
    BEGIN
        IF p_status_type NOT IN ('Delayed', 'Suspended', 'Rerouted', 'Normal') THEN
            RAISE_APPLICATION_ERROR(-20002, 'Invalid status type. Must be Delayed, Suspended, Rerouted, or Normal.');
        END IF;

        -- Verify incident exists
        SELECT 1 INTO v_dummy FROM INCIDENT WHERE IncidentID = p_incident_id;
        -- Verify segment exists
        SELECT 1 INTO v_dummy FROM SEGMENT WHERE SegmentID = p_segment_id;

        INSERT INTO AFFECTEDSEGMENT (IncidentID, SegmentID, StatusType, DelayMinutes)
        VALUES (p_incident_id, p_segment_id, p_status_type, NVL(p_delay_minutes, 0));

        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003, 'Incident ID or Segment ID does not exist.');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_DISRUPT_SEGMENT;

    PROCEDURE PRC_DISRUPT_STATION (
        p_incident_id   IN  NUMBER,
        p_station_id    IN  NUMBER,
        p_status_type   IN  VARCHAR2,
        p_reason        IN  VARCHAR2
    ) IS
        v_dummy NUMBER;
    BEGIN
        IF p_status_type NOT IN ('Open', 'PartiallyClosed', 'Closed', 'Congested') THEN
            RAISE_APPLICATION_ERROR(-20004, 'Invalid station status. Must be Open, PartiallyClosed, Closed, or Congested.');
        END IF;

        SELECT 1 INTO v_dummy FROM INCIDENT WHERE IncidentID = p_incident_id;
        SELECT 1 INTO v_dummy FROM STATION WHERE StationID = p_station_id;

        INSERT INTO AFFECTEDSTATION (IncidentID, StationID, StatusType, Reason)
        VALUES (p_incident_id, p_station_id, p_status_type, p_reason);

        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, 'Incident ID or Station ID does not exist.');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_DISRUPT_STATION;

    PROCEDURE PRC_RESOLVE_INCIDENT (
        p_incident_id   IN  NUMBER
    ) IS
    BEGIN
        UPDATE INCIDENT
        SET EndTime = SYSTIMESTAMP
        WHERE IncidentID = p_incident_id;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20006, 'Incident not found with ID: ' || p_incident_id);
        END IF;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_RESOLVE_INCIDENT;

    PROCEDURE PRC_ADD_STATION (
        p_name          IN  VARCHAR2,
        p_city          IN  VARCHAR2,
        p_lat           IN  NUMBER,
        p_lng           IN  NUMBER,
        p_address       IN  VARCHAR2,
        o_station_id    OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO STATION (Name, City, Latitude, Longitude, Address, IsActive)
        VALUES (p_name, p_city, p_lat, p_lng, p_address, 1)
        RETURNING StationID INTO o_station_id;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_ADD_STATION;

    PROCEDURE PRC_TOPUP_WALLET (
        p_card_number   IN  VARCHAR2,
        p_amount        IN  NUMBER,
        p_reference     IN  VARCHAR2,
        o_new_balance   OUT NUMBER
    ) IS
        v_wallet_id NUMBER;
        v_balance   NUMBER(10,2);
    BEGIN
        IF p_amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20007, 'Top-up amount must be strictly greater than zero.');
        END IF;

        -- Lock wallet row for update
        SELECT w.WalletID, w.Balance
        INTO v_wallet_id, v_balance
        FROM WALLET w
        JOIN SMARTCARD sc ON w.SmartCardID = sc.SmartCardID
        WHERE sc.CardNumber = p_card_number AND sc.IsActive = 1
        FOR UPDATE;

        UPDATE WALLET
        SET Balance = Balance + p_amount,
            LastUpdated = SYSTIMESTAMP
        WHERE WalletID = v_wallet_id
        RETURNING Balance INTO o_new_balance;

        INSERT INTO TRANSACTION (WalletID, TransactionType, Amount, Timestamp, Status, Reference)
        VALUES (v_wallet_id, 'TopUp', p_amount, SYSTIMESTAMP, 'Completed', NVL(p_reference, 'ADMIN-TOPUP'));

        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20008, 'Active SmartCard not found for card number: ' || p_card_number);
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PRC_TOPUP_WALLET;

END PKG_BETTERTRAVEL_ADMIN;
/

-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 05: RECURSIVE CTE ROUTING ENGINE & FARE DEDUCTION
-- Implements Oracle Recursive CTE graph traversal with live disruption avoidance,
-- transfer penalty calculation, and transactional ticketing/smartcard operations.
-- ============================================================================

CREATE OR REPLACE PACKAGE PKG_TRANSIT_ROUTER AS

    -- Structure for ranked route results
    TYPE t_route_option IS RECORD (
        PathRank            NUMBER,
        StationPath         VARCHAR2(1000),
        RoutePath           VARCHAR2(1000),
        ModesUsed           VARCHAR2(200),
        TotalMinutes        NUMBER,
        TotalDistanceKm     NUMBER(8,2),
        TransferCount       NUMBER,
        TotalBaseFare       NUMBER(8,2),
        DiscountedFare      NUMBER(8,2),
        HasDelays           NUMBER(1),
        TotalDelayMinutes   NUMBER
    );

    TYPE t_route_options_tbl IS TABLE OF t_route_option;

    -- Pipelined function for querying ranked routes in SQL views/REST endpoints
    FUNCTION FIND_ROUTES (
        p_origin_station_id IN NUMBER,
        p_dest_station_id   IN NUMBER,
        p_fare_class_id     IN NUMBER DEFAULT 1,
        p_max_transfers     IN NUMBER DEFAULT 3
    ) RETURN t_route_options_tbl PIPELINED;

    -- SmartCard Tap-In (Journey Initiation)
    PROCEDURE PROCESS_TAP_IN (
        p_card_number       IN  VARCHAR2,
        p_from_station_id   IN  NUMBER,
        o_journey_leg_id    OUT NUMBER,
        o_passenger_name    OUT VARCHAR2,
        o_current_balance   OUT NUMBER
    );

    -- SmartCard Tap-Out (Journey Completion & Atomic Wallet Deduction)
    PROCEDURE PROCESS_TAP_OUT (
        p_card_number       IN  VARCHAR2,
        p_to_station_id     IN  NUMBER,
        o_journey_leg_id    OUT NUMBER,
        o_fare_deducted     OUT NUMBER,
        o_new_balance       OUT NUMBER,
        o_journey_status    OUT VARCHAR2
    );

END PKG_TRANSIT_ROUTER;
/

CREATE OR REPLACE PACKAGE BODY PKG_TRANSIT_ROUTER AS

    FUNCTION FIND_ROUTES (
        p_origin_station_id IN NUMBER,
        p_dest_station_id   IN NUMBER,
        p_fare_class_id     IN NUMBER DEFAULT 1,
        p_max_transfers     IN NUMBER DEFAULT 3
    ) RETURN t_route_options_tbl PIPELINED IS
        v_discount_pct NUMBER := 0;
    BEGIN
        -- Fetch discount percentage for fare class
        BEGIN
            SELECT DiscountPercentage INTO v_discount_pct
            FROM FARECLASS
            WHERE FareClassID = p_fare_class_id AND IsActive = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_discount_pct := 0;
        END;

        -- Recursive CTE Traversal
        FOR r IN (
            WITH 
            -- 1. Active physical edges (excluding suspended segments)
            ACTIVE_NETWORK_EDGES AS (
                SELECT 
                    seg.SegmentID,
                    seg.RouteID,
                    r.Name AS RouteName,
                    r."Mode" AS TransitMode,
                    st_from.StationID AS FromStationID,
                    st_from.Name AS FromStationName,
                    st_to.StationID AS ToStationID,
                    st_to.Name AS ToStationName,
                    seg.Distance,
                    seg.ScheduledTime,
                    NVL(aff.DelayMinutes, 0) AS DelayMinutes,
                    (seg.ScheduledTime + NVL(aff.DelayMinutes, 0)) AS EdgeDuration,
                    NVL(sf.BaseAmount, 2.00) AS SegmentFare
                FROM SEGMENT seg
                JOIN ROUTE r ON seg.RouteID = r.RouteID AND r.IsActive = 1
                JOIN ROUTESTOP rs_from ON seg.FromRouteStopID = rs_from.RouteStopID AND rs_from.IsActive = 1
                JOIN STATION st_from ON rs_from.StationID = st_from.StationID AND st_from.IsActive = 1
                JOIN ROUTESTOP rs_to ON seg.ToRouteStopID = rs_to.RouteStopID AND rs_to.IsActive = 1
                JOIN STATION st_to ON rs_to.StationID = st_to.StationID AND st_to.IsActive = 1
                LEFT JOIN SEGMENTFARE sf ON seg.SegmentID = sf.SegmentID 
                    AND sf.IsActive = 1
                    AND SYSTIMESTAMP BETWEEN sf.ValidFrom AND NVL(sf.ValidTo, SYSTIMESTAMP + INTERVAL '1' DAY)
                LEFT JOIN (
                    -- Active disruptions
                    SELECT a.SegmentID, a.StatusType, a.DelayMinutes
                    FROM AFFECTEDSEGMENT a
                    JOIN INCIDENT i ON a.IncidentID = i.IncidentID
                    WHERE SYSTIMESTAMP BETWEEN i.StartTime AND NVL(i.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
                ) aff ON seg.SegmentID = aff.SegmentID
                WHERE seg.IsActive = 1
                  -- BYPASS SUSPENDED EDGES COMPLETELY
                  AND (aff.StatusType IS NULL OR aff.StatusType <> 'Suspended')
                  -- Avoid completely closed stations
                  AND st_from.StationID NOT IN (
                      SELECT afs.StationID FROM AFFECTEDSTATION afs
                      JOIN INCIDENT inc ON afs.IncidentID = inc.IncidentID
                      WHERE afs.StatusType = 'Closed'
                        AND SYSTIMESTAMP BETWEEN inc.StartTime AND NVL(inc.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
                  )
                  AND st_to.StationID NOT IN (
                      SELECT afs.StationID FROM AFFECTEDSTATION afs
                      JOIN INCIDENT inc ON afs.IncidentID = inc.IncidentID
                      WHERE afs.StatusType = 'Closed'
                        AND SYSTIMESTAMP BETWEEN inc.StartTime AND NVL(inc.EndTime, SYSTIMESTAMP + INTERVAL '1' DAY)
                  )
            ),
            
            -- 2. Walking transfers between distinct stations
            WALKING_EDGES AS (
                SELECT 
                    0 AS SegmentID,
                    0 AS RouteID,
                    'Walk' AS RouteName,
                    'Walk' AS TransitMode,
                    spt.FromStationID,
                    st_from.Name AS FromStationName,
                    spt.ToStationID,
                    st_to.Name AS ToStationName,
                    (spt.WalkingDistance / 1000.0) AS Distance,
                    spt.WalkingTime AS ScheduledTime,
                    0 AS DelayMinutes,
                    spt.WalkingTime AS EdgeDuration,
                    0.00 AS SegmentFare
                FROM STATION_PAIR_TRANSFER spt
                JOIN STATION st_from ON spt.FromStationID = st_from.StationID AND st_from.IsActive = 1
                JOIN STATION st_to ON spt.ToStationID = st_to.StationID AND st_to.IsActive = 1
            ),

            -- 3. Unified graph edges
            GRAPH_EDGES AS (
                SELECT * FROM ACTIVE_NETWORK_EDGES
                UNION ALL
                SELECT * FROM WALKING_EDGES
            ),

            -- 4. Recursive Path Search with Cycle Prevention
            ROUTING_CTE (
                CurrentStationID,
                CurrentStationName,
                LastRouteID,
                StationPath,
                RoutePath,
                ModesPath,
                TotalMinutes,
                TotalDistanceKm,
                TransferCount,
                TotalBaseFare,
                TotalDelayMinutes,
                HopCount
            ) AS (
                -- Base Anchor Member: First hop from origin
                SELECT 
                    e.ToStationID,
                    e.ToStationName,
                    e.RouteID,
                    CAST(e.FromStationName || ' -> ' || e.ToStationName AS VARCHAR2(1000)),
                    CAST(e.RouteName AS VARCHAR2(1000)),
                    CAST(e.TransitMode AS VARCHAR2(200)),
                    e.EdgeDuration,
                    e.Distance,
                    0 AS TransferCount,
                    e.SegmentFare,
                    e.DelayMinutes,
                    1 AS HopCount
                FROM GRAPH_EDGES e
                WHERE e.FromStationID = p_origin_station_id

                UNION ALL

                -- Recursive Member: Traverse to next station
                SELECT 
                    nxt.ToStationID,
                    nxt.ToStationName,
                    nxt.RouteID,
                    CAST(r.StationPath || ' -> ' || nxt.ToStationName AS VARCHAR2(1000)),
                    CAST(
                        CASE 
                            WHEN r.LastRouteID = nxt.RouteID OR nxt.RouteID = 0 THEN r.RoutePath
                            ELSE r.RoutePath || ' -> ' || nxt.RouteName
                        END AS VARCHAR2(1000)
                    ),
                    CAST(
                        CASE 
                            WHEN INSTR(r.ModesPath, nxt.TransitMode) > 0 THEN r.ModesPath
                            ELSE r.ModesPath || ', ' || nxt.TransitMode
                        END AS VARCHAR2(200)
                    ),
                    -- Factor in transfer penalty (5 min default or ROUTETRANSFER lookup)
                    r.TotalMinutes + nxt.EdgeDuration + (
                        CASE 
                            WHEN r.LastRouteID <> nxt.RouteID AND r.LastRouteID <> 0 AND nxt.RouteID <> 0 
                            THEN 5 
                            ELSE 0 
                        END
                    ),
                    r.TotalDistanceKm + nxt.Distance,
                    r.TransferCount + (
                        CASE 
                            WHEN r.LastRouteID <> nxt.RouteID AND r.LastRouteID <> 0 AND nxt.RouteID <> 0 
                            THEN 1 
                            ELSE 0 
                        END
                    ),
                    r.TotalBaseFare + nxt.SegmentFare,
                    r.TotalDelayMinutes + nxt.DelayMinutes,
                    r.HopCount + 1
                FROM ROUTING_CTE r
                JOIN GRAPH_EDGES nxt ON r.CurrentStationID = nxt.FromStationID
                WHERE INSTR(r.StationPath, nxt.ToStationName) = 0 -- Loop check
                  AND r.HopCount < 8                             -- Max depth guard
                  AND r.TransferCount <= p_max_transfers
            )
            CYCLE CurrentStationID SET is_cycle TO 1 DEFAULT 0

            -- Filter paths that reached destination
            SELECT 
                ROW_NUMBER() OVER (ORDER BY TotalMinutes ASC, TotalBaseFare ASC) AS PathRank,
                StationPath,
                RoutePath,
                ModesPath,
                TotalMinutes,
                TotalDistanceKm,
                TransferCount,
                TotalBaseFare,
                ROUND(TotalBaseFare * (1.0 - (v_discount_pct / 100.0)), 2) AS DiscountedFare,
                CASE WHEN TotalDelayMinutes > 0 THEN 1 ELSE 0 END AS HasDelays,
                TotalDelayMinutes
            FROM ROUTING_CTE
            WHERE CurrentStationID = p_dest_station_id
              AND is_cycle = 0
            FETCH FIRST 5 ROWS ONLY
        ) LOOP
            PIPE ROW(t_route_option(
                r.PathRank,
                r.StationPath,
                r.RoutePath,
                r.ModesPath,
                r.TotalMinutes,
                r.TotalDistanceKm,
                r.TransferCount,
                r.TotalBaseFare,
                r.DiscountedFare,
                r.HasDelays,
                r.TotalDelayMinutes
            ));
        END LOOP;

        RETURN;
    END FIND_ROUTES;

    PROCEDURE PROCESS_TAP_IN (
        p_card_number       IN  VARCHAR2,
        p_from_station_id   IN  NUMBER,
        o_journey_leg_id    OUT NUMBER,
        o_passenger_name    OUT VARCHAR2,
        o_current_balance   OUT NUMBER
    ) IS
        v_card_id       NUMBER;
        v_passenger_id  NUMBER;
        v_fare_class    VARCHAR2(60) := 'Standard Adult';
        v_balance       NUMBER(10,2);
        v_open_leg_id   NUMBER;
    BEGIN
        -- 1. Validate SmartCard and get Passenger & Wallet details
        SELECT 
            sc.SmartCardID,
            sc.PassengerID,
            p.FirstName || ' ' || p.LastName,
            w.Balance
        INTO v_card_id, v_passenger_id, o_passenger_name, v_balance
        FROM SMARTCARD sc
        JOIN PASSENGER p ON sc.PassengerID = p.PassengerID
        JOIN WALLET w ON sc.SmartCardID = w.SmartCardID
        WHERE sc.CardNumber = p_card_number 
          AND sc.IsActive = 1
          AND w.IsActive = 1
          AND sc.ExpiryDate > SYSTIMESTAMP;

        -- 2. Validate minimum balance ($2.00 minimum for tap-in)
        IF v_balance < 2.00 THEN
            RAISE_APPLICATION_ERROR(-20010, 'Insufficient wallet balance ($' || TO_CHAR(v_balance, 'FM990.00') || '). Minimum $2.00 required to enter.');
        END IF;

        -- 3. Check for unfinished journeys (tap-in without tap-out)
        BEGIN
            SELECT JourneyLegID INTO v_open_leg_id
            FROM JOURNEYLEG
            WHERE SmartCardID = v_card_id AND Status = 'InProgress';

            IF v_open_leg_id IS NOT NULL THEN
                -- Auto-charge penalty fare on abandoned journey
                UPDATE JOURNEYLEG
                SET Status = 'Incomplete',
                    FareDeducted = 5.00,
                    TapOutTime = SYSTIMESTAMP
                WHERE JourneyLegID = v_open_leg_id;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
        END;

        -- 4. Get active fare class
        BEGIN
            SELECT fc.Name INTO v_fare_class
            FROM PASSENGERFARECLASS pfc
            JOIN FARECLASS fc ON pfc.FareClassID = fc.FareClassID
            WHERE pfc.PassengerID = v_passenger_id 
              AND pfc.VerificationStatus = 'Approved'
              AND SYSTIMESTAMP BETWEEN pfc.ValidFrom AND NVL(pfc.ValidTo, SYSTIMESTAMP + INTERVAL '1' DAY)
            FETCH FIRST 1 ROWS ONLY;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_fare_class := 'Standard Adult';
        END;

        -- 5. Create new Journey Leg
        INSERT INTO JOURNEYLEG (
            SmartCardID,
            PassengerID,
            FromStationID,
            TapInTime,
            FareDeducted,
            FareClassAtTime,
            Status
        ) VALUES (
            v_card_id,
            v_passenger_id,
            p_from_station_id,
            SYSTIMESTAMP,
            0.00,
            v_fare_class,
            'InProgress'
        ) RETURNING JourneyLegID INTO o_journey_leg_id;

        o_current_balance := v_balance;
        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20011, 'SmartCard not found, expired, or deactivated: ' || p_card_number);
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PROCESS_TAP_IN;

    PROCEDURE PROCESS_TAP_OUT (
        p_card_number       IN  VARCHAR2,
        p_to_station_id     IN  NUMBER,
        o_journey_leg_id    OUT NUMBER,
        o_fare_deducted     OUT NUMBER,
        o_new_balance       OUT NUMBER,
        o_journey_status    OUT VARCHAR2
    ) IS
        v_card_id       NUMBER;
        v_wallet_id     NUMBER;
        v_balance       NUMBER(10,2);
        v_from_stat_id  NUMBER;
        v_calc_fare     NUMBER(8,2) := 2.50; -- Default base trip fare
        v_discount_pct  NUMBER := 0;
        v_fare_class    VARCHAR2(60);
    BEGIN
        -- 1. Find active journey leg
        SELECT 
            jl.JourneyLegID,
            jl.SmartCardID,
            jl.FromStationID,
            jl.FareClassAtTime,
            w.WalletID,
            w.Balance
        INTO 
            o_journey_leg_id,
            v_card_id,
            v_from_stat_id,
            v_fare_class,
            v_wallet_id,
            v_balance
        FROM JOURNEYLEG jl
        JOIN SMARTCARD sc ON jl.SmartCardID = sc.SmartCardID
        JOIN WALLET w ON sc.SmartCardID = w.SmartCardID
        WHERE sc.CardNumber = p_card_number
          AND jl.Status = 'InProgress'
        FOR UPDATE OF w.Balance;

        -- 2. Prevent same-station tap-out within 2 minutes without fare
        IF v_from_stat_id = p_to_station_id THEN
            v_calc_fare := 0.00;
        ELSE
            -- Compute optimal route fare using router function
            BEGIN
                SELECT DiscountedFare INTO v_calc_fare
                FROM TABLE(PKG_TRANSIT_ROUTER.FIND_ROUTES(v_from_stat_id, p_to_station_id))
                WHERE ROWNUM = 1;
            EXCEPTION
                WHEN OTHERS THEN
                    v_calc_fare := 2.50;
            END;
        END IF;

        -- 3. Atomic wallet deduction
        IF v_balance < v_calc_fare THEN
            -- Allow completion but balance goes negative / flagged
            o_journey_status := 'CompletedWithArrears';
        ELSE
            o_journey_status := 'Completed';
        END IF;

        UPDATE WALLET
        SET Balance = Balance - v_calc_fare,
            LastUpdated = SYSTIMESTAMP
        WHERE WalletID = v_wallet_id
        RETURNING Balance INTO o_new_balance;

        -- 4. Record Transaction
        INSERT INTO TRANSACTION (WalletID, TransactionType, Amount, Timestamp, Status, Reference)
        VALUES (v_wallet_id, 'FareDeduction', v_calc_fare, SYSTIMESTAMP, 'Completed', 'JOURNEY-' || o_journey_leg_id);

        -- 5. Finalize Journey Leg
        UPDATE JOURNEYLEG
        SET ToStationID = p_to_station_id,
            TapOutTime = SYSTIMESTAMP,
            FareDeducted = v_calc_fare,
            Status = 'Completed'
        WHERE JourneyLegID = o_journey_leg_id;

        o_fare_deducted := v_calc_fare;
        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20012, 'No active InProgress journey found for SmartCard: ' || p_card_number);
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END PROCESS_TAP_OUT;

END PKG_TRANSIT_ROUTER;
/

