-- ============================================================================
-- BETTERTRAVEL: MULTI-MODAL TRANSIT SYSTEM
-- SCRIPT 01: DATABASE SCHEMA DDL
-- Compatible with Oracle Database 19c, 21c, and 23ai Free
-- ============================================================================

SET SQLBLANKLINES ON;

-- Clean up existing objects in reverse dependency order
BEGIN
    FOR t IN (
        SELECT table_name FROM all_tables 
        WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
          AND table_name IN (
            'JOURNEYROUTE', 'JOURNEYLEG', 'TRANSACTION', 'WALLET', 'SMARTCARD',
            'PASSENGERFARECLASS', 'PASSENGER', 'FARECLASS', 'SEGMENTFARE',
            'AFFECTEDSTATION', 'AFFECTEDSEGMENT', 'INCIDENT',
            'ROUTETRANSFER', 'STATION_PAIR_TRANSFER', 'SEGMENT', 'ROUTESTOP',
            'ROUTE', 'STATION'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- SPATIAL GRAPH ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE STATION (
    StationID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(100)       NOT NULL,
    City                VARCHAR2(60)        NOT NULL,
    Latitude            NUMBER(9,6)         NOT NULL,
    Longitude           NUMBER(9,6)         NOT NULL,
    Address             VARCHAR2(255),
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_STATION_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE ROUTE (
    RouteID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(100)       NOT NULL,
    "Mode"              VARCHAR2(20)        NOT NULL,
    Operator            VARCHAR2(100)       NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_ROUTE_MODE CHECK ("Mode" IN ('Metro', 'Bus', 'Train')),
    CONSTRAINT CHK_ROUTE_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE ROUTESTOP (
    RouteStopID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RouteID             NUMBER              NOT NULL,
    StationID           NUMBER              NOT NULL,
    Sequence            NUMBER(4)           NOT NULL,
    PlatformNumber      VARCHAR2(20),
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_ROUTESTOP_ROUTE   FOREIGN KEY (RouteID)   REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_ROUTESTOP_STATION FOREIGN KEY (StationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROUTE_SEQUENCE    UNIQUE (RouteID, Sequence),
    CONSTRAINT CHK_ROUTESTOP_ACTIVE CHECK (IsActive IN (0, 1))
);

CREATE TABLE SEGMENT (
    SegmentID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RouteID             NUMBER              NOT NULL,
    FromRouteStopID     NUMBER              NOT NULL,
    ToRouteStopID       NUMBER              NOT NULL,
    Distance            NUMBER(6,2)         NOT NULL, -- kilometers
    ScheduledTime       NUMBER(4)           NOT NULL, -- minutes
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SEGMENT_ROUTE         FOREIGN KEY (RouteID)         REFERENCES ROUTE(RouteID)         ON DELETE CASCADE,
    CONSTRAINT FK_SEGMENT_FROMSTOP      FOREIGN KEY (FromRouteStopID) REFERENCES ROUTESTOP(RouteStopID) ON DELETE CASCADE,
    CONSTRAINT FK_SEGMENT_TOSTOP        FOREIGN KEY (ToRouteStopID)   REFERENCES ROUTESTOP(RouteStopID) ON DELETE CASCADE,
    CONSTRAINT UQ_SEGMENT_PAIR          UNIQUE (RouteID, FromRouteStopID, ToRouteStopID),
    CONSTRAINT CHK_SEGMENT_ACTIVE       CHECK (IsActive IN (0, 1)),
    CONSTRAINT CHK_SEGMENT_DISTANCE     CHECK (Distance > 0),
    CONSTRAINT CHK_SEGMENT_TIME         CHECK (ScheduledTime > 0)
);

-- ----------------------------------------------------------------------------
-- TRANSFER ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE STATION_PAIR_TRANSFER (
    TransferID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FromStationID       NUMBER              NOT NULL,
    ToStationID         NUMBER              NOT NULL,
    WalkingDistance     NUMBER(6)           NOT NULL, -- meters
    WalkingTime         NUMBER(4)           NOT NULL, -- minutes
    IsDirectConnection  NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SPTRANSFER_FROMSTATION FOREIGN KEY (FromStationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT FK_SPTRANSFER_TOSTATION   FOREIGN KEY (ToStationID)   REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_SPTRANSFER_PAIR        UNIQUE (FromStationID, ToStationID),
    CONSTRAINT CHK_SPTRANSFER_DIFF       CHECK (FromStationID <> ToStationID),
    CONSTRAINT CHK_SPTRANSFER_DIRECT     CHECK (IsDirectConnection IN (0, 1))
);

CREATE TABLE ROUTETRANSFER (
    RouteTransferID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FromRouteID         NUMBER              NOT NULL,
    ToRouteID           NUMBER              NOT NULL,
    CommonStationID     NUMBER              NOT NULL,
    TransferTime        NUMBER(4)           NOT NULL, -- minutes
    MinimumWaitTime     NUMBER(4)           DEFAULT 2 NOT NULL, -- minutes
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_RTRANSFER_FROMROUTE   FOREIGN KEY (FromRouteID)     REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_RTRANSFER_TOROUTE     FOREIGN KEY (ToRouteID)       REFERENCES ROUTE(RouteID)     ON DELETE CASCADE,
    CONSTRAINT FK_RTRANSFER_STATION     FOREIGN KEY (CommonStationID) REFERENCES STATION(StationID) ON DELETE CASCADE,
    CONSTRAINT UQ_RTRANSFER_CONFIG      UNIQUE (FromRouteID, ToRouteID, CommonStationID),
    CONSTRAINT CHK_RTRANSFER_DIFF       CHECK (FromRouteID <> ToRouteID),
    CONSTRAINT CHK_RTRANSFER_ACTIVE     CHECK (IsActive IN (0, 1))
);

-- ----------------------------------------------------------------------------
-- DISRUPTION ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE INCIDENT (
    IncidentID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title               VARCHAR2(150)       NOT NULL,
    Description         VARCHAR2(1000),
    StartTime           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    EndTime             TIMESTAMP,
    Severity            VARCHAR2(20)        NOT NULL,
    CONSTRAINT CHK_INCIDENT_SEVERITY CHECK (Severity IN ('Minor', 'Moderate', 'Major', 'Critical')),
    CONSTRAINT CHK_INCIDENT_TIMEFRAME CHECK (EndTime IS NULL OR EndTime >= StartTime)
);

CREATE TABLE AFFECTEDSEGMENT (
    AffectedSegmentID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IncidentID          NUMBER              NOT NULL,
    SegmentID           NUMBER              NOT NULL,
    StatusType          VARCHAR2(20)        NOT NULL,
    DelayMinutes        NUMBER(4)           DEFAULT 0 NOT NULL,
    CONSTRAINT FK_AFFSEG_INCIDENT FOREIGN KEY (IncidentID) REFERENCES INCIDENT(IncidentID) ON DELETE CASCADE,
    CONSTRAINT FK_AFFSEG_SEGMENT  FOREIGN KEY (SegmentID)  REFERENCES SEGMENT(SegmentID)   ON DELETE CASCADE,
    CONSTRAINT CHK_AFFSEG_STATUS  CHECK (StatusType IN ('Delayed', 'Suspended', 'Rerouted', 'Normal'))
);

CREATE TABLE AFFECTEDSTATION (
    AffectedStationID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IncidentID          NUMBER              NOT NULL,
    StationID           NUMBER              NOT NULL,
    StatusType          VARCHAR2(20)        NOT NULL,
    Reason              VARCHAR2(255),
    CONSTRAINT FK_AFFSTAT_INCIDENT FOREIGN KEY (IncidentID) REFERENCES INCIDENT(IncidentID) ON DELETE CASCADE,
    CONSTRAINT FK_AFFSTAT_STATION  FOREIGN KEY (StationID)  REFERENCES STATION(StationID)   ON DELETE CASCADE,
    CONSTRAINT CHK_AFFSTAT_STATUS  CHECK (StatusType IN ('Open', 'PartiallyClosed', 'Closed', 'Congested'))
);

-- ----------------------------------------------------------------------------
-- PRICING ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE FARECLASS (
    FareClassID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name                VARCHAR2(60)        NOT NULL,
    DiscountPercentage  NUMBER(5,2)         DEFAULT 0.00 NOT NULL,
    RequiresVerification NUMBER(1)          DEFAULT 0 NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT CHK_FARECLASS_DISCOUNT CHECK (DiscountPercentage BETWEEN 0 AND 100),
    CONSTRAINT CHK_FARECLASS_VERIF    CHECK (RequiresVerification IN (0, 1)),
    CONSTRAINT CHK_FARECLASS_ACTIVE   CHECK (IsActive IN (0, 1))
);

CREATE TABLE SEGMENTFARE (
    SegmentFareID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SegmentID           NUMBER              NOT NULL,
    BaseAmount          NUMBER(8,2)         NOT NULL,
    ValidFrom           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ValidTo             TIMESTAMP,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SEGFARE_SEGMENT   FOREIGN KEY (SegmentID) REFERENCES SEGMENT(SegmentID) ON DELETE CASCADE,
    CONSTRAINT CHK_SEGFARE_AMOUNT   CHECK (BaseAmount >= 0),
    CONSTRAINT CHK_SEGFARE_ACTIVE   CHECK (IsActive IN (0, 1)),
    CONSTRAINT CHK_SEGFARE_TIMEFRAME CHECK (ValidTo IS NULL OR ValidTo >= ValidFrom)
);

-- ----------------------------------------------------------------------------
-- PASSENGER & ACCOUNT ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE PASSENGER (
    PassengerID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email               VARCHAR2(150)       NOT NULL CONSTRAINT UQ_PASSENGER_EMAIL UNIQUE,
    FirstName           VARCHAR2(60)        NOT NULL,
    LastName            VARCHAR2(60)        NOT NULL,
    DateOfBirth         DATE,
    Phone               VARCHAR2(30),
    RegistrationDate    TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE PASSENGERFARECLASS (
    PassengerFareClassID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PassengerID         NUMBER              NOT NULL,
    FareClassID         NUMBER              NOT NULL,
    ValidFrom           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ValidTo             TIMESTAMP,
    VerificationStatus  VARCHAR2(20)        DEFAULT 'Pending' NOT NULL,
    CONSTRAINT FK_PFC_PASSENGER FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT FK_PFC_FARECLASS FOREIGN KEY (FareClassID) REFERENCES FARECLASS(FareClassID) ON DELETE CASCADE,
    CONSTRAINT CHK_PFC_STATUS   CHECK (VerificationStatus IN ('Pending', 'Approved', 'Rejected', 'Expired'))
);

CREATE TABLE SMARTCARD (
    SmartCardID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PassengerID         NUMBER              NOT NULL,
    CardNumber          VARCHAR2(30)        NOT NULL CONSTRAINT UQ_SMARTCARD_NUM UNIQUE,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    ActivationDate      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    ExpiryDate          TIMESTAMP           NOT NULL,
    CONSTRAINT FK_SMARTCARD_PASSENGER FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT CHK_SMARTCARD_ACTIVE   CHECK (IsActive IN (0, 1))
);

CREATE TABLE WALLET (
    WalletID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SmartCardID         NUMBER              NOT NULL CONSTRAINT UQ_WALLET_SMARTCARD UNIQUE,
    Balance             NUMBER(10,2)        DEFAULT 0.00 NOT NULL,
    LastUpdated         TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    IsActive            NUMBER(1)           DEFAULT 1 NOT NULL,
    CONSTRAINT FK_WALLET_SMARTCARD FOREIGN KEY (SmartCardID) REFERENCES SMARTCARD(SmartCardID) ON DELETE CASCADE,
    CONSTRAINT CHK_WALLET_BALANCE  CHECK (Balance >= 0.00),
    CONSTRAINT CHK_WALLET_ACTIVE   CHECK (IsActive IN (0, 1))
);

-- ----------------------------------------------------------------------------
-- TRANSACTION & JOURNEY ENTITIES
-- ----------------------------------------------------------------------------

CREATE TABLE TRANSACTION (
    TransactionID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WalletID            NUMBER              NOT NULL,
    TransactionType     VARCHAR2(20)        NOT NULL,
    Amount              NUMBER(10,2)        NOT NULL,
    Timestamp           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    Status              VARCHAR2(20)        DEFAULT 'Completed' NOT NULL,
    Reference           VARCHAR2(100),
    CONSTRAINT FK_TX_WALLET  FOREIGN KEY (WalletID) REFERENCES WALLET(WalletID) ON DELETE CASCADE,
    CONSTRAINT CHK_TX_TYPE   CHECK (TransactionType IN ('TopUp', 'FareDeduction', 'Refund', 'Adjustment')),
    CONSTRAINT CHK_TX_STATUS CHECK (Status IN ('Pending', 'Completed', 'Failed', 'Reversed'))
);

CREATE TABLE JOURNEYLEG (
    JourneyLegID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SmartCardID         NUMBER              NOT NULL,
    PassengerID         NUMBER              NOT NULL,
    FromStationID       NUMBER              NOT NULL,
    ToStationID         NUMBER,
    TapInTime           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    TapOutTime          TIMESTAMP,
    FareDeducted        NUMBER(8,2)         DEFAULT 0.00 NOT NULL,
    FareClassAtTime     VARCHAR2(60)        NOT NULL,
    Status              VARCHAR2(20)        DEFAULT 'InProgress' NOT NULL,
    CONSTRAINT FK_JLEG_SMARTCARD FOREIGN KEY (SmartCardID)   REFERENCES SMARTCARD(SmartCardID) ON DELETE CASCADE,
    CONSTRAINT FK_JLEG_PASSENGER FOREIGN KEY (PassengerID)   REFERENCES PASSENGER(PassengerID) ON DELETE CASCADE,
    CONSTRAINT FK_JLEG_FROMSTAT  FOREIGN KEY (FromStationID) REFERENCES STATION(StationID),
    CONSTRAINT FK_JLEG_TOSTAT    FOREIGN KEY (ToStationID)   REFERENCES STATION(StationID),
    CONSTRAINT CHK_JLEG_STATUS   CHECK (Status IN ('InProgress', 'Completed', 'Cancelled', 'Incomplete'))
);

CREATE TABLE JOURNEYROUTE (
    JourneyRouteUsedID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JourneyLegID        NUMBER              NOT NULL,
    RouteID             NUMBER              NOT NULL,
    Sequence            NUMBER(3)           DEFAULT 1 NOT NULL,
    BoardingTime        TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    AlightingTime       TIMESTAMP,
    CONSTRAINT FK_JROUTE_LEG   FOREIGN KEY (JourneyLegID) REFERENCES JOURNEYLEG(JourneyLegID) ON DELETE CASCADE,
    CONSTRAINT FK_JROUTE_ROUTE FOREIGN KEY (RouteID)      REFERENCES ROUTE(RouteID)           ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- PERFORMANCE INDEXES
-- ----------------------------------------------------------------------------

CREATE INDEX IDX_ROUTESTOP_STATION   ON ROUTESTOP(StationID);
CREATE INDEX IDX_SEGMENT_ROUTE       ON SEGMENT(RouteID);
CREATE INDEX IDX_SEGMENT_FROMSTOP    ON SEGMENT(FromRouteStopID);
CREATE INDEX IDX_SEGMENT_TOSTOP      ON SEGMENT(ToRouteStopID);
CREATE INDEX IDX_RTRANSFER_COMMON    ON ROUTETRANSFER(CommonStationID, FromRouteID, ToRouteID);
CREATE INDEX IDX_AFFSEG_LOOKUP       ON AFFECTEDSEGMENT(SegmentID, StatusType);
CREATE INDEX IDX_AFFSTAT_LOOKUP      ON AFFECTEDSTATION(StationID, StatusType);
CREATE INDEX IDX_INCIDENT_ACTIVE     ON INCIDENT(StartTime, EndTime);
CREATE INDEX IDX_SEGFARE_LOOKUP      ON SEGMENTFARE(SegmentID, IsActive);
CREATE INDEX IDX_TRANSACTION_WALLET  ON TRANSACTION(WalletID, Timestamp);
CREATE INDEX IDX_JOURNEYLEG_CARD     ON JOURNEYLEG(SmartCardID, Status);
